# Команда build должна собирать исполняемый файл с именем solution
build:
	gcc -o solution Untitled-2.c
# Здесь должна быть команда для сборки решения, например:
# g++ -o solution solution.cpp

# Команда test должна запускать исполняемый файл solution с входным файлом и сохранять результат в выходной файл
# make test INPUT_FILE=path/to/input.txt OUTPUT_FILE=path/to/output.txt
test:
	./solution ${INPUT_FILE} > ${OUTPUT_FILE}