# Решение должно принимать путь к входному файлу первым аргументом
# и печатать ответ в stdout.
#
# Команда build должна собирать исполняемый файл с именем solution.py.
build:
# Здесь должна быть команда для сборки решения, например:
# g++ -o solution.py solution.py.cpp

# Команда test запускает solution.py, передавая путь ко входному файлу
# первым аргументом, а stdout перенаправляет в OUTPUT_FILE.
# make test INPUT_FILE=path/to/input.txt OUTPUT_FILE=path/to/output.txt
test:
	./solution ${INPUT_FILE} > ${OUTPUT_FILE}
